### ISSUE TITLE
Auth!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-todo-list-tutorial#37]
# todo
+ [x] Create new file: `auth.md`
+ [x] Add tutorial using `auth_plug` to add authentication to the Todo App
+ [x] "Lift and Shift" from: https://github.com/dwyl/phoenix-chat-example/pull/120
+ [x] Tests.

**Comment by nelsonic** [comment]
@LuchoTurtle are you looking at this next? 💭

**Comment by LuchoTurtle** [comment]
I am, just trying to fix some tests that broke 
Quite a few of them :/

**Comment by LuchoTurtle** [comment]
@nelsonic this should be ready for review. The PR has been already pushed for review 👍

**Comment by nelsonic** [comment]
Please ensure the tests pass and have 100% coverage. 🙏
