### ISSUE TITLE
Heroku Ping

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-todo-list-tutorial#38]
At present the heroku app takes _ages_ to boot when the person viewing the tutorial first clicks the link. "Ages" is not a scientific measure, but it _feels_ like forever and it reflects poorly on the App when in _reality_ Phoenix is _fast_ and the server-side rendered (and cached) Todo List is _much_ faster than any client-side implementation could ever be!

# Todo

+ [ ] Borrow the code from our `email` app which has the same problem!
https://github.com/dwyl/email/blob/b4c2c4f4d96773c326cf3fa8cd4838973c9a78f5/lib/app_web/controllers/sent_controller.ex#L132-L147
+ [ ] Make a _generic_ solution that can be implemented in _any_ of or projects that are deployed to Heroku
+ [ ] Implement it in the Todo List Tutorial to wake up the Heroku Dyno using a Pixel/GIF rendered in the `README.md`

**Comment by nelsonic** [comment]
https://hex.pm/packages/ping
![image](https://user-images.githubusercontent.com/194400/83319580-b6ae5200-a237-11ea-865a-0154835ea50e.png)
