### ISSUE TITLE
Feat: Todo List `REST API`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-todo-list-tutorial#53]
Once deployed to Fly.io with CI/CD #52 and `auth` is added #37 
we should add a _basic_ `REST API` endpoint to `CRUD` Todo List items.

# Why?

As part of building a full-stack App using our chosen Tech Stack https://github.com/dwyl/technology-stack#the-petal-stack
We want to build the backend API in `Phoenix`.
This mini tutorial is the perfect place to showcase building such an API because all the ground-work is already done for Todo list `items`. 

# Todo

+ [x] in the _same_ Phoenix App, create a new `api_controller.ex` for `CRUD`-ing the `Todo` list `items` (you can use `:pipe_through :json`).
  > Remember our objective is to leverage as _much_ of the existing work in this repo as possible. 🙏 
+ [x] Create an API Endpoint for `Creating` a `new` todo list `item` and test it via `cURL` (or `Postman`) 
  + [x] Should accept a `JSON` payload with the necessary data, e.g: 
  1. `person_id` (`Int`)
  2. `status` (`Int`)
  3. `text` (`String`)

https://github.com/dwyl/phoenix-todo-list-tutorial/blob/e945ed2082e7d1f38f4eb13dc383986d26869826/lib/app/todo/item.ex#L5-L8
  + [x] Should create a new Todo `item` if the data is valid

+ [x] Create a `REST API` Endpoint for `editing` the `Todo` list `item.text`:
  + [x] Signature: `POST /items/:id/`
  + [x] Should accept the `item.id` (`Int`) and `item.text` (`String`) and return `200` if successful. 🆗 

+ [x] Create `REST API` Endpoint for Updating the `status` of the `item` i.e. setting it to "done" ✅ 

## Relevant Learning

Please read: https://github.com/dwyl/phoenix-content-negotiation-tutorial 👀 
And if you have any questions regarding content negotiation please open an issue. 🆕 

For ***`this`*** project we don't need to have all the same routes we just need:
1. Create 🆕 
2. Edit 📝 
3. Update status ✅

**Comment by nelsonic** [comment]
@LuchoTurtle assigning this to you. But if anything is unclear please comment. 💬 🙏

**Comment by nelsonic** [comment]
@LuchoTurtle please see: https://github.com/dwyl/hits/issues/168 🔗
